version: '3'
services: 
    app:
        container_name: Fries_and_ketchup
        restart: always
        build: .
        ports: 
            - '80:3000'
        links:
            - mongo
    mongo:
        container_name: mongodbfries
        image: mongo
        ports: 
            - '27017:27017'